title: 邢予泓 Sing Yuhong
email: h9c2511@gmail.com
description: >-
  國立臺東大學 | 光電研究生 | 量子點發光二極體 QD-LED 製程與效率分析 | Python 自動化分析與跨領域實作
baseurl: "" # for GitHub Pages 留空
url: "https://bbbb520-yh.github.io" # 改成你的 GitHub Pages 網址

# 社群與連結設定（方便 future include 使用）
github_username: bbbb520-yh
linkedin_username: sing-yuhong

# Collections（可擴充 blog, portfolio, talks）
markdown: kramdown
theme: minima

# Navigation list (optional for menu)
nav:
  - title: 關於我
    url: "#about"
  - title: 技能
    url: "#skills"
  - title: 專案
    url: "#projects"
  - title: 學歷
    url: "#education"
  - title: 聯絡
    url: "#contact"


# 不要部署這些目錄
exclude: ['package.json', 'src', 'node_modules', 'vendor']


