# _config.yml
title: "邢予泓 Sing Yuhong"
name: "邢予泓"
english_name: "Sing Yuhong"
email: "h9c2511@gmail.com"
github_username: "bbbb520-yh"
description: "國立臺東大學｜量子點 LED｜薄膜製程｜Python"


baseurl: "" # for GitHub Pages 留空
url: "https://bbbb520-yh.github.io" # 改成你的 GitHub Pages 網址

# 社群與連結設定（方便 future include 使用）
github_username: bbbb520-yh
linkedin_username: sing-yuhong

# Collections（可擴充 blog, portfolio, talks）
markdown: kramdown
theme: minima

# Navigation list (optional for menu)
nav:
  - title: 關於我
    url: "#about"
  - title: 技能
    url: "#skills"
  - title: 專案
    url: "#projects"
  - title: 學歷
    url: "#education"
  - title: 活動參與
    url: "#activities"
  - title: 語言能力
    url: "#languages"
  - title: 聯絡
    url: "#contact"


# 不要部署這些目錄
exclude: ['package.json', 'src', 'node_modules', 'vendor']


